### ISSUE TITLE
The inference cost with pytorch1.0

### ISSUE THREAD

**Issue by wenbinTse** [csmliu/AdaDSR#3]
Hi, thanks for your work.

I'm trying to reproduce your work with pytorch1.0 and cuda9.0.  The PSNR performance is similar to the paper's. However, the sparse network costs more time than the normal network. In Set5 benchmark, each image costs about 383 ms using the sparse network and 281ms using the normal network.

Why the speed becomes slow?

**Comment by csmliu** [comment]
Because the normal convolution is Winograd based (and highly optimized in cuDNN), while our implementation is im2col based. Thus the running speed is limited by the implementation of the sparse convolution.

**Comment by wenbinTse** [comment]
Thanks for the reply.
Does it mean the reported results of EDSR and ADAEDSR in Table 2 are both based on your im2col-based convolution?

**Comment by csmliu** [comment]
Yes. And this has been declared in Sec. 4.1 `Model Evaluation`.
