### ISSUE TITLE
Benchmark performance

### ISSUE THREAD

**Issue by wenbinTse** [csmliu/AdaDSR#4]
Hi,

I reproduce your work recently and the result using your applied model weight was so strange.

The PSNR in set5 is about 38.21 which is normal but the performance in set14(32.61),  b100(28.54) and urban100(30.20) is so bad.

I followed your script and changed nothing to the code.
Could you tell what may cause the problem?

Thanks a lot.

**Comment by csmliu** [comment]
Sorry for the late response.

Do you mean that you just cloned the repo and downloaded the pretrained models, and used the exact command provided in the README to train an AdaEDSR?

**Comment by wenbinTse** [comment]
Yes, I did. Besides, I also evaluated the model `ckpt/adaedsr_x2/AdaEDSR_model.pth` directly and got similar results.

**Comment by csmliu** [comment]
Could you please show your command to test the provided model? I have downloaded this repo and the provided models, and get exactly the same PSNR as given in the paper.

**Comment by csmliu** [comment]
My command is `python test.py --model adaedsr --name adaedsr_x2 --scale 2 --load_path ./ckpt/adaedsr_x2/AdaEDSR_model.pth --datasetname set5 set14 b100 urban100 manga109 --depth 32 --chop True --matlab True --gpu_ids 0`.
Using `--sparse_conv True` and `--matlab True` or not should have minor influence on the results.

**Comment by wenbinTse** [comment]
My command is `python test.py --model adaedsr --name adaedsr_x2 --scale 2 --load_path ./ckpt/adaedsr_x2/AdaEDSR_model.pth --datasetname set5 set14 b100 urban100 --depth 32 --chop True`

**Comment by csmliu** [comment]
I use exactly the same command, and still get the same results.
Which version of PyTorch are you using, and are you using the provided datasets? (You can also use the datasets given by RCAN, they are totally the same)
I will download the provided zip file containing the datasets and test again.

Besides, could you please test RCAN using the following command?
`python test.py --model rcan --name rcan_x2 --scale 2 --load_path ./pretrained/RCAN_BIX2.pth --dataset_name set5 set14 b100 urban100 manga109 --chop True`

**Comment by wenbinTse** [comment]
I am using pytorch1.0 as my server only supports it. The datasets used is downloaded from their official website.

I will test EDSR and RCAN using the provided datasets.

Anyway, thanks a lot for your reply and your work.

**Comment by csmliu** [comment]
Well, I only tested the code on PyTorch 1.2, 1.3, 1.5 and 1.6, but it should work on PyTorch 1.0.
Downloading from the official website is okay, but I remember that there are some pre-processing steps (following previous works like EDSR and RCAN), so please follow the README to process the data.
If you cannot get the same PSNR of RCAN, then there must be something goes wrong (and it's very likely to be the data processing).

**Comment by csmliu** [comment]
I'm going to close this issue. Please feel free to reopen it or open a new one if there are any further problems.
