### ISSUE TITLE
How to do inference?

### ISSUE THREAD

**Issue by Damanotra** [csmliu/AdaDSR#5]
Is there any quickstart command for doing inference? Where should I put the custom data and what is the command line? Thank you

**Comment by csmliu** [comment]
The test command has been provided in the README.
If  you want to use your custom images:
1) if you have both LR/HR images
    please organize them as the provided test data (e.g., `set5`)
2) if you have LR images only
    please modify the code (e.g., `data/benchmark.py` for loading LR images only and `test.py` for not calculating PSNR)

For both conditions, the path of your data should be provided by `--dataroot PATH`

**Comment by Damanotra** [comment]
Thank you for your fast response. I only have LR images, and I tried to modify data/benchmark.py for only loading LR images, then several errors regarding HR images come up and I already commented all code related to HR images that appear in call stack

btw this is what I call 

python test.py --model adarcan --name adarcan_x2 --scale 2 --load_path ./ckpt/adarcan_x2/AdaRCAN_model.pth --dataset_name set5 --depth 20 --matlab False --gpu_ids -1 --multi_imreader False

Now I stuck with this and I don't know what more should I do
![image](https://user-images.githubusercontent.com/29616545/96631683-d528fd00-1340-11eb-90a5-a88a12beb14b.png)

Don't mind the inference.py, it's same with test.py but with all HR codes commented. 
Can you help me, please? Thank you so much

**Comment by Damanotra** [comment]
Nevermind, I already solve it, the benchmark dataset change my files name adding "_LRBI_" in the middle.

Thank you for your help. I might be going back here if anything goes wrong again. It would be cool if you prepare/make quickstart command line for inference (only inference, no Y data) in all paper/models/git you create
