### ISSUE TITLE
Question about table3 in the paper

### ISSUE THREAD

**Issue by Booooooooooo** [csmliu/AdaDSR#6]
Thank you for your amazing work.
I got a little confused in your ablation analysis. For example, in your work you trained FAdaEDSR(8) with a fixed depth d=8. And I noticed that the performance of FAdaEDSR(8)(38.17dB) is better than EDSR(8)(38.05dB). Why would this happen? In my understanding, the performance of EDSR should be the upper bound of FAdaEDSR because FAdaEDSR has less modules. Do I have any misunderstandings? Or does "fixed depth d=8" mean the desired depth?
Thanks in advance. : )

**Comment by csmliu** [comment]
FAdaEDSR (8) has the same structure as AdaEDSR, the difference is that FAdaEDSR (8) is trained with d=8 in L_depth (Eqn. (7)), but AdaEDSR is trained with d randomly sampled from [0,32].

**Comment by Booooooooooo** [comment]
Okay, got it! Thank you so much!
