### ISSUE TITLE
there are some differences between the paper and the code

### ISSUE THREAD

**Issue by Feihongzhu** [csmliu/AdaDSR#7]
Thank you for your work! I seem to feel that there are some differences between the paper and the code. I would like you to explain the following doubts.

1. The adapter module generate the mask for each residual block in the paper, but it generate the mask( size is [N,1,W,H]) in the code. Is this True？Why?
2. If the first question is correct, then the number of masks corresponds to the batch of feature map. How to reflect the adaptation here?
3. Why the  input depth of the adapter module is randomly generated？
4. Can this adapter module set the mask corresponding to the places with more texture or rich details in the feature map to non-zero, and the mask corresponding to the color smooth area or low-frequency area to zero?

**Comment by csmliu** [comment]
Hi there,

Thanks for your interests.
1. Yes, the adapter generates a mask for each residual block, and it is also right that it generates a [N, 1, H, W] map (this is the depth map, not mask). In each residual block, the depth map is transformed to a mask by Eqn. (4) (see [the code](https://github.com/csmliu/AdaDSR/blob/master/models/dsr_model.py#L171-L174)).
2. Sorry that I didn't fully understand your question, please refer to the response of the first question.
3. We hope that the trained model can adapt to various depth during the inference phase without retraining, thus in the training procedure, the input depth is randomly generated. In the test phase, you can assign the depth by `--depth DEPTH` option.
4. No for the current code, but you can modify the depth as a 2D mask (see [the code](https://github.com/csmliu/AdaDSR/blob/master/models/dsr_model.py#L321)).

**Comment by Florrie-Giu** [comment]
Thanks for your quick response. 

1. In each residual block, the depth map which size is [N, 1, H, W] is transformed to a mask by Eqn(4). Then, for each residual block, the masks are all the same?   
4. The Class Predictor in the [code](https://github.com/csmliu/AdaDSR/blob/master/models/dsr_model.py#L298) is the adapter module in the paper?

**Comment by Feihongzhu** [comment]
Thanks for your rapid response. I don’t quite understand the paper, but I am very interested in the idea of your paper.

1. The number of the depth map is batch size [N], but it doesn't relate to the number of the residual block.  For each residual block, N masks will be calculated from N depth maps according to Eqn(4), so the mask size also is [N,1, H, W]?  
3.  During training, how to operate the generated mask and convolution to calculate? Corresponding to the image area where the mask is zero, is the convolution calculation also zero?
4. Is the Class Predictor in the code[(see the code)](https://github.com/csmliu/AdaDSR/blob/master/models/dsr_model.py#L298)  the adapter module in the paper ？

**Comment by csmliu** [comment]
1. You can refer to Fig. 2. For each sample (input image), we only need to predict a single depth map for a set of residual blocks, which is [N, 1, H, W], and the values range from 0 to D (the number of residual blocks). For a pixel in a certain residual block, e.g., the second one (there is one residual in front of it), assume the value of depth map for this pixel is `d`, then the mask value is 0 if `d < 1`, the mask value is 1 if `d > 2`, otherwise, the mask value is `d - 1`. 
2. During training, vanilla convolution is deployed, and the value is set to zero by a multiplication operation. During the inference phase, the mask is taken as an input of the sparse convolution, and the corresponding regions are skipped.
3. Yes.

**Comment by Feihongzhu** [comment]
Thank you for your serious reply, I will read this paper carefully and seek your discussion！
