### ISSUE TITLE
input resolution for calculating the number of flops

### ISSUE THREAD

**Issue by nanmehta** [csmliu/AdaDSR#8]
can you please help me to know, what is the input size for which number of flops has been calculated for all the scale factors?

**Comment by csmliu** [comment]
For example, when calculating the FLOPs for Set5 (x2), all images in Set5 dataset are downscaled by a scale factor 2 (also by `Prepare_TestData_HR_LR.m` provided in the test data zipped file), whose FLOPs are calculated one by one in [test.py#L134](https://github.com/csmliu/AdaDSR/blob/8997b5f978cb7fae2e61b6753a950dcae7ead470/test.py#L134).

Finally, the FLOPs index is an average on all these images.
